const sampleData = {
  products: [
    {
      id: 1,
      name: 'Футболка Sara Sporting Stretch',
      slug: 'sara-sporting-stretch-shirt',
      category: "Мужские рубашки",
      description: 'Классический стиль Sara с современным комфортом',
      images: [
        '/images/sample-products/p1-1.jpg',
        '/images/sample-products/p1-2.jpg',
      ],
      price: 59.99,
      brand: 'Sara',
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: 'banner-1.jpg',
    },
    {
      id: 2,
      name: 'Длинно-рукавная рубашка Luke Pro',
      slug: 'luke-pro-long-sleeved-shirt',
      category: "Мужские рубашки",
      description: 'Вневременной стиль и премиальный комфорт',
      images: [
        '/images/sample-products/p2-1.jpg',
        '/images/sample-products/p2-2.jpg',
      ],
      price: 85.9,
      brand: 'Luke Pro',
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: 'banner-2.jpg',
    },
    {
      id: 3,
      name: 'Классическая рубашка Tommy Hilfiger',
      slug: 'tommy-hilfiger-classic-fit-dress-shirt',
      category: "Мужские рубашки",
      description: 'Совершенный баланс изысканности и комфорта',
      images: [
        '/images/sample-products/p3-1.jpg',
        '/images/sample-products/p3-2.jpg',
      ],
      price: 99.95,
      brand: 'Tommy Hilfiger',
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      id: 4,
      name: 'Тонкая рубашка Calvin Klein',
      slug: 'calvin-klein-slim-fit-stretch-shirt',
      category: "Мужские рубашки",
      description: 'Современный дизайн с эластичной тканью',
      images: [
        '/images/sample-products/p4-1.jpg',
        '/images/sample-products/p4-2.jpg',
      ],
      price: 39.95,
      brand: 'Calvin Klein',
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      id: 5,
      name: 'Оксфордская рубашка Sara Ralph Lauren',
      slug: 'sara-ralph-lauren-oxford-shirt',
      category: "Мужские рубашки",
      description: 'Иконический дизайн Sara с изысканной тканью',
      images: [
        '/images/sample-products/p5-1.jpg',
        '/images/sample-products/p5-2.jpg',
      ],
      price: 79.99,
      brand: 'Sara',
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
    },
    {
      id: 6,
      name: 'Розовая худи Sara Classic',
      slug: 'sara-classic-pink-hoodie',
      category: "Мужские толстовки",
      description: 'Мягкая, стильная и идеальная для расслабленных дней',
      images: [
        '/images/sample-products/p6-1.jpg',
        '/images/sample-products/p6-2.jpg',
      ],
      price: 99.99,
      brand: 'Sara',
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
    },
  ],
};

export default sampleData;

